---
output: # rmarkdown::github_document
  html_document:
  word_document: default
  pdf_document: default
title: "Building shiny apps"
runtime: shiny
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      warning=FALSE, message=FALSE)
```

```{r}
library(tidyverse)
library(shiny)

d = read_csv('titanic.csv')

variables_names = names(d)

ui <- fluidPage(
  
  titlePanel("Density Plot"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      selectInput(
        inputId ="var1",
        label = "Select a Numeric Variables",
        choices = variables_names, selected = "Age"
      ),
      
      selectInput(
        inputId ="var2",
        label = "Select a Categorical Variables",
        choices = variables_names,
        selected = "Sex"
      )
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      
      plotOutput(outputId = 'show_plot')
    )
  )
)

# server is a function! 
server <- function(input, output) {
  
  
  output$show_plot <- renderPlot({
    d = read_csv('titanic.csv')
    v1 = input$var1
    v2 = input$var2
   
    
    library(ggplot2)
      
    r = ggplot(d, aes(x = d[[v1]], color = as.factor(d[[v2]])))+
        geom_density()+
        labs(x = v1, color = v2)
      
    return(r)
    
    
  })
  
}
# app
shinyApp(ui = ui, server = server)
```


```{r}
library(tidyverse)
library(shiny)
library(DT)

ui <- fluidPage(
  
  titlePanel("Visualization"),
  
  sidebarLayout(
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      fileInput('f1', label = 'Upload data for visualization', accept = '.csv'),
      
      selectInput('v1', label='Select a Numeric Variable', choices=''),
      selectInput('v2', label='Select a Categorical Variable', choices='')
    
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      plotOutput(outputId = 'show_plot')
    )
  )
)

# server
server <- function(input, output, session) {
  
  myData <- reactive({
    inFile = input$f1
    if (is.null(inFile)) return(NULL)
    data <- read.csv(inFile$datapath, header = TRUE)
    data
  }
    )
    
  output$show_plot <- renderPlot({
  
    inFile = input$f1
    v1 = input$v1
    d <- read.csv(inFile$datapath, header = TRUE)
    
    v1 = input$v1
    v2 = input$v2
    
    
      library(ggplot2)
      
      r = ggplot(d, aes(x = d[[v1]], color = as.factor(d[[v2]])))+
        geom_density()+
        labs(x = v1, color = v2)
      
    return(r)
    
  })
  
  
  observeEvent(input$f1,{ 
    inFile = input$f1
    data <- read.csv(inFile$datapath, header = TRUE)   
               updateSelectInput(session, 'v1', choices = names(data))}
               )
  
  observeEvent(input$f1,{ 
    inFile = input$f1
    data <- read.csv(inFile$datapath, header = TRUE)   
    updateSelectInput(session, 'v2', choices = names(data))}
  )

}


shinyApp(ui = ui, server = server)

```


```{r}
library(shiny)
library(rattle)

# Read in the data
library(tidyverse)
titanic = read_csv("titanic.csv")

# Remove some columns
titanic$PassengerId =  NULL
titanic$Ticket =  NULL
titanic$Name = NULL
titanic$Cabin = NULL

# Correct variables' types
names(titanic)[1] = "target"  # change Survived to target
titanic$target = factor(titanic$target)
titanic$Pclass = factor(titanic$Pclass)

# Handle missing values

titanic$Age[is.na(titanic$Age)] = mean(titanic$Age, na.rm = TRUE)

# Model Building 

titanic = drop_na(titanic)

# Split 70% training, 30% testing
library(caret)
splitIndex <- createDataPartition(titanic$target, p = .70, list = FALSE, times = 1)
train <- titanic[ splitIndex,]
test <- titanic[-splitIndex,]

# 
library(rpart) #load the rpart package





######################################
ui <- fluidPage(
  
  titlePanel("Decision Tree for Titanic"),
  
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      sliderInput('depth','Max Depth', min = 1, max = 5, value = 1)
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      

      plotOutput(outputId = 'blah1'),
      plotOutput(outputId = 'blah2')
    )
  )
)

############################################
server <- function(input, output) {
  
  output$blah1 <- renderPlot({
    max_depth = input$depth
    mytree2 <- rpart(target ~ ., data = train, method = "class", control = rpart.control(maxdepth = max_depth))
    fancyRpartPlot(mytree2)
  })
  

  
}
# app
shinyApp(ui = ui, server = server)

# deployApp()

```

```{r}
library(tidyverse)
library(shiny)
library(DT)

ui <- fluidPage(
  
  titlePanel("Model"),
  
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      fileInput('f1', label = 'Upload data', accept = '.csv'),
      
      selectInput('y', label='Select target variable', choices=c('')),
      
      checkboxGroupInput("x", label = "Select input variables"),
      
      sliderInput('depth', label = 'Decide the max depth', min = 1, max = 5, value = 1)
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      plotOutput(outputId = 'tree')
    )
  )
)

# server
server <- function(input, output, session) {
  
  myData <- reactive({
    inFile = input$f1
    if (is.null(inFile)) return(NULL)
    data <- read.csv(inFile$datapath, header = TRUE)
    data
  }
    )
    
  output$tree <- renderPlot({
  
    inFile = input$f1
    d <- read_csv(inFile$datapath)
    v1 = input$y
    v2 = as.numeric(input$x)
    d = cbind(d[,v1], d[,v2])
    names(d)[1]='target'
    print(v2)
    max_depth = input$depth
    library(rpart)
    library(rattle)
    set.seed(2019)
    mytree2 <- rpart(target ~., data = d, method = "class", control = rpart.control(maxdepth = max_depth))
    fancyRpartPlot(mytree2)
    
  })
  
  
  observeEvent(input$f1,{ 
    inFile = input$f1
    data <- read.csv(inFile$datapath, header = TRUE)   
               updateSelectInput(session, 'y', choices = names(data))}
               )
  
  observeEvent(input$f1,{ 
    inFile = input$f1
    data <- read.csv(inFile$datapath, header = TRUE)
    choices = as.list(c(1:ncol(data)))
    names(choices)= names(data)
    updateCheckboxGroupInput(session, 'x', choices = choices)}
  )
  
}
# app
shinyApp(ui = ui, server = server)
```


```{r}
library(tidyverse)
library(shiny)

d <- read_csv('https://covidtracking.com/data/download/all-states-history.csv')


choices = names(table(d$state))

variables_names = names(d)

ui <- fluidPage(
  
  titlePanel("Density Plot"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      checkboxGroupInput(inputId = "x", label = "Select state to compare",
                         choices = choices, inline = TRUE),
      
      
      selectInput(inputId ='v1', label='Select a Numeric Variable', choices=variables_names)
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      
      verbatimTextOutput("print_text"),
      
      
      imageOutput(outputId = 'show_plot'),
      
      imageOutput(outputId = 'show_plot2')
    )
  )
)

# server is a function! 
server <- function(input, output) {
  
  output$print_text <- renderPrint({
    
    library(tidyverse)
    library(gganimate)
    # r <- d %>% 
    #   filter(state %in% choices[input$x]) %>% 
    #   ggplot(aes(y=positive,
    #              x=date,
    #              color=state))+ 
    #   geom_line()+
    #   geom_point(size=3)+
    #   geom_text(aes(label = positive), 
    #             hjust = -.1, size=5) +
    #   transition_reveal(date)
    
    print(class(input$v1))
    
    
  })
  
  
  output$show_plot <- renderPlot({
    
    library(tidyverse)
    library(ggplot2)
    library(gganimate)
    
    v1 = input$v1
    
    d <- d %>% 
      filter(state %in% input$x)
    
    ggplot(d, aes_string(y=v1,
                 x='date',
                 color='state'))+ 
      geom_line()
    
  }    
)
  
  output$show_plot2 <- renderPlot({
    
    library(tidyverse)
    library(ggplot2)
    library(gganimate)
    
    v1 = input$v1
    
    d <- d %>% 
      filter(state %in% input$x)
    
    ggplot(d, aes_string(y=v1,
                         x='date',
                         color='state'))+ 
      geom_line()
    
  }    
  )
  
  
}

shinyApp(ui = ui, server = server)
```

```{r}
library(tidyverse)
library(shiny)

d <- read_csv('https://covidtracking.com/data/download/all-states-history.csv')


choices = names(table(d$state))

variables_names = names(d)

ui <- fluidPage(
  
  titlePanel("Density Plot"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      checkboxGroupInput(inputId = "x", label = "Select state to compare",
                         choices = choices, inline = TRUE),
      
      
      selectInput(inputId ='v1', label='Select a Numeric Variable', choices=variables_names)
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      
      verbatimTextOutput("print_text"),
      
      
      imageOutput(outputId = 'show_plot'),
      
      imageOutput(outputId = 'show_plot2')
    )
  )
)


ui <- navbarPage("Navbar!",
           tabPanel("Plot",
                    
                    fluidPage(
                      
                      titlePanel("Density Plot"),
                      
                      sidebarLayout(
                        
                        sidebarPanel(
                          
                          checkboxGroupInput(inputId = "x", label = "Select state to compare",
                                             choices = choices, inline = TRUE),
                          
                          
                          selectInput(inputId ='v1', label='Select a Numeric Variable', choices=variables_names)
                          
                        ),
                        
                        # Main panel for displaying outputs ----
                        mainPanel(
                          
                          # Output: Histogram ----
                          
                          verbatimTextOutput("print_text"),
                          
                          
                          imageOutput(outputId = 'show_plot'),
                          
                          imageOutput(outputId = 'show_plot2')
                        )
                      )
                    )
                    
                    
                    
                    
                    
                    ),
           tabPanel("Summary",
                    verbatimTextOutput("summary")
           )
)



# server is a function! 
server <- function(input, output) {
  
  output$print_text <- renderPrint({
    
    library(tidyverse)
    library(gganimate)
    # r <- d %>% 
    #   filter(state %in% choices[input$x]) %>% 
    #   ggplot(aes(y=positive,
    #              x=date,
    #              color=state))+ 
    #   geom_line()+
    #   geom_point(size=3)+
    #   geom_text(aes(label = positive), 
    #             hjust = -.1, size=5) +
    #   transition_reveal(date)
    
    print(class(input$v1))
    
    
  })
  
  
  output$show_plot <- renderPlot({
    
    library(tidyverse)
    library(ggplot2)
    library(gganimate)
    
    v1 = input$v1
    
    d <- d %>% 
      filter(state %in% input$x)
    
    ggplot(d, aes_string(y=v1,
                 x='date',
                 color='state'))+ 
      geom_line()
    
  }    
)
  
  output$show_plot2 <- renderPlot({
    
    library(tidyverse)
    library(ggplot2)
    library(gganimate)
    
    v1 = input$v1
    
    d <- d %>% 
      filter(state %in% input$x)
    
    ggplot(d, aes_string(y=v1,
                         x='date',
                         color='state'))+ 
      geom_line()
    
  }    
  )
  
  
}

shinyApp(ui = ui, server = server)
```

```{r}
library(tidyverse)
library(shiny)

d <- read_csv('https://covidtracking.com/data/download/all-states-history.csv')

choices = names(table(d$state))

variables_names = names(d)

first_date = min(d$date)

current_date = max(d$date)
                     

ui <- fluidPage(
  
  titlePanel("Density Plot"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      checkboxGroupInput(inputId = "x", label = "Select state to compare",
                         choices = choices, inline = TRUE),
      
      
      selectInput(inputId ='v1', label='Select a Numeric Variable', choices=variables_names),
      
      sliderInput(inputId = "date",
                  "Select Date Range:",
                  min = first_date,
                  max = current_date,
                  value= c(first_date, current_date),
                  timeFormat="%d %b")
      
    ),
  
    mainPanel(
      
      verbatimTextOutput("print_text"),
      
      
      imageOutput(outputId = 'show_plot'),
      
      imageOutput(outputId = 'show_plot2')
    )
  )
)

# server is a function! 
server <- function(input, output) {
  
  output$print_text <- renderPrint({
    
    library(tidyverse)
    library(gganimate)
    # r <- d %>% 
    #   filter(state %in% choices[input$x]) %>% 
    #   ggplot(aes(y=positive,
    #              x=date,
    #              color=state))+ 
    #   geom_line()+
    #   geom_point(size=3)+
    #   geom_text(aes(label = positive), 
    #             hjust = -.1, size=5) +
    #   transition_reveal(date)
    
    print(class(input$v1))
    
    
  })
  
  
  output$show_plot <- renderPlot({
    
    library(tidyverse)
    library(ggplot2)
    library(gganimate)
    
    v1 = input$v1
    
    d <- d %>% 
      filter(state %in% input$x, date>input$date[1], date<input$date[2])
    
    ggplot(d, aes_string(y=v1,
                 x='date',
                 color='state'))+ 
      geom_line()
    
  }    
)
  
  output$show_plot2 <- renderPlot({
    
    library(tidyverse)
    library(ggplot2)
    library(gganimate)
    
    v1 = input$v1
    
    d <- d %>% 
      filter(state %in% input$x)
    
    ggplot(d, aes_string(y=v1,
                         x='date',
                         color='state'))+ 
      geom_line()
    
  }    
  )
  
  
}

shinyApp(ui = ui, server = server)
```

```{r}
library(tidyverse)
library(shiny)

d <- read_csv('https://covidtracking.com/data/download/all-states-history.csv')

write.csv(d, 'covid19.csv', row.names = FALSE)

choices = c('CA', 'FL', 'TX', 'MA', 'NY')

variables_names = names(d)

first_date = min(d$date)

current_date = max(d$date)
                     

ui <- fluidPage(
  
  titlePanel("Covid 19 by States"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      checkboxGroupInput(inputId = "x", label = "Select state to compare",
                         choices = choices, inline = TRUE),
      
      
      selectInput(inputId ='v1', label='Select a Numeric Variable', choices=variables_names),
      
      sliderInput(inputId = "date",
                  "Select Date Range:",
                  min = first_date,
                  max = current_date,
                  value= c(first_date, current_date),
                  timeFormat="%d %b"),
      
      radioButtons(inputId = "plot_choice", 
                   h3("Select Plot:"),
                   c("Line Plot" = "line",
                     "Point Plot" = "point"),
                   selected = 'line'),
      
    ),
  
    mainPanel(
      
      imageOutput(outputId = 'show_plot')
    )
  )
)

# server is a function! 
server <- function(input, output) {
  
  output$show_plot <- renderPlot({
    
    library(tidyverse)
    library(ggplot2)
    library(gganimate)
    
    v1 = input$v1
    
    d <- d %>% 
      filter(state %in% input$x, date>input$date[1], date<input$date[2])
    
    if(input$plot_choice == 'line')
    {
      ggplot(d, aes_string(y=v1,
                           x='date',
                           color='state'))+ 
        geom_line()  
    }
    
    else{
      ggplot(d, aes_string(y=v1,
                           x='date',
                           color='state'))+ 
        geom_point()
    }
    
  }    
)
  
  
}

shinyApp(ui = ui, server = server)
```

```{r}


library(tidyverse)
library(shiny)

d <- read_csv('titanic.csv')

d <- d %>% select(Survived, Pclass, Sex, Age)

d$Pclass <- factor(d$Pclass)
d$Sex <- factor(d$Sex)
d$Survived <- factor(d$Survived)

d <- drop_na(d)

models = c('ranger', 'rpart', 'glmnet', 'rpart2', 'gbm')

variables_names = names(d)


ui <- fluidPage(
  
  titlePanel("Covid 19 by States"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      checkboxGroupInput(inputId = "mod", label = "Select models to compare",
                         choices = models, inline = TRUE),
      
      
      selectInput(inputId ='target_variable', label='Select target Variable', choices=variables_names),
      
      checkboxGroupInput(inputId = "input_variables", label = "Select input variables",
                         choices = variables_names, inline = TRUE),
      
    ),
  
    mainPanel(
      
      imageOutput(outputId = 'show_plot')
    )
  )
)

# server is a function! 
server <- function(input, output) {
  
  output$show_plot <- renderPlot({
    
    library(tidyverse)
    library(ggplot2)
    library(caret)
    
    mod = input$mod
    
    d <- d %>% select(input$target_variable, input$input_variables)
    
    names(d)[1] <- 'target'
    
    model_list = list()
    
    for (i in 1:length(mod))
    {
      set.seed(2020)
      model_list[[i]] <- train(target~., data=d, 
                      method = mod[i])
    }
    
    names(model_list) = mod
    results <- resamples(model_list)
    bwplot(results)
  }    
)
  
  
}

shinyApp(ui = ui, server = server)
```



```{r}




models = c('ranger', 'rpart', 'glmnet', 'rpart2', 'gbm')

ui <- fluidPage(
  
  titlePanel("Covid 19 by States"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      fileInput('f1', label = 'Upload data for visualization', accept = '.csv'),
      
      checkboxGroupInput(inputId = "mod", label = "Select models to compare",
                         choices = models, inline = TRUE),
      
      
      selectInput(inputId ='target_variable', label='Select target Variable', choices = ''),
      
      checkboxGroupInput(inputId = "input_variables", label = "Select input variables",
                         inline = TRUE, choices = ''),
      
    ),
  
    mainPanel(
      
      imageOutput(outputId = 'show_plot')
    )
  )
)

# server is a function! 
server <- function(input, output, session) {
  library(shiny)
  
  myData <- reactive({
    inFile = input$f1
    if (is.null(inFile)) return(NULL)
    data <- read_csv(inFile$datapath)
    data
  }
  )
  
  output$show_plot <- renderPlot({
    
    library(tidyverse)
    library(ggplot2)
    library(caret)
    
    mod = input$mod
    
    
    inFile = input$f1

    d <- read_csv(inFile$datapath)
    
    d <- as_tibble(d)
    
    d <- d %>% select(input$target_variable, input$input_variables)
    
    d <- drop_na(d)
    
    names(d)[1] <- 'target'
    
    d$target <- as.factor(d$target)
    
    model_list = list()
    
    for (i in 1:length(mod))
    {
      set.seed(2020)
      model_list[[i]] <- train(target~., data=d, 
                      method = mod[i])
    }
    
    names(model_list) = mod
    results <- resamples(model_list)
    bwplot(results)
  }    
)
  
  
  observeEvent(input$f1,{ 
    inFile = input$f1
    data <- read_csv(inFile$datapath)   
    updateSelectInput(session, 'target_variable', choices = names(data))}
  )
  
  observeEvent(input$f1,{ 
    inFile = input$f1
    data <- read_csv(inFile$datapath)
    choices = as.list(c(1:ncol(data)))
    updateCheckboxGroupInput(session, 'input_variables', choices = names(data))}
  )
  
  
}

shinyApp(ui = ui, server = server)
```

