---
title: "Titanic - SelectInput"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    logo: logo.png
    source_code: embed
    social: menu

runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(flexdashboard)
library(tidyverse)
library(plotly)
library(knitr)
library(DT)
df <- read_csv('https://bryantstats.github.io/math421/data/titanic.csv')
df <- drop_na(df, Age) 
df$Survived = factor(df$Survived)

titanic_sex <- unique(df$Sex)
```

{.sidebar}
=======================================================================

Waiting time between eruptions and the duration of the eruption for the
Old Faithful geyser in Yellowstone National Park, Wyoming, USA.

```{r}
selectInput(inputId = "input1", 
            label = "Select Gender:",
            choices = titanic_sex, 
            selected = 'male')
```

Main Tab 1
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Density Plot

```{r}
renderPlotly({
  p1 <- df %>% filter(Sex==input$input1) %>% 
    ggplot(aes(x=Age, color=Survived))+
    geom_density()
  ggplotly(p1)
})
```

Column {data-width=500}
-----------------------------------------------------------------------

### Bar Plot

```{r}
renderPlotly({
  p2 <- df %>% filter(Sex==input$input1) %>% 
    ggplot(aes(x=Pclass, fill=Survived))+
    geom_bar()
  ggplotly(p2)
})
```
