
---
title: "Tidymodels"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: united
  word_document:
    toc: yes
  pdf_document:
    toc: yes
---

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Train a model


```{r}
library(tidyverse)
library(tidymodels)


titanic_train <- read_csv('https://bryantstats.github.io/math421/data/titanic.csv')
library(tidymodels)

# data pre-processing
titanic_recipe <- 
  recipe(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked, 
         data = titanic_train) %>% # keep variables we want
  step_impute_median(Age,Fare) %>% # imputation
  step_impute_mode(Embarked) %>% # imputation
  step_mutate_at(Survived, Pclass, Sex, Embarked, fn = factor) %>% # make these factors
  step_mutate(Travelers = SibSp + Parch + 1) %>% # new variable
  step_rm(SibSp, Parch) %>% # remove variables
  step_dummy(all_nominal_predictors()) %>% # create indicator variables
  step_normalize(all_numeric_predictors()) # normalize numerical variables


titanic_rf_spec <-  
  rand_forest(trees = 1000) %>% # algorithm speicfic argument:1000 trees
  set_engine('ranger') %>% 
  set_mode('classification')

# To check tunable parameters
rand_forest() %>% tunable()
decision_tree() %>% tunable()
# List of models can be found here: https://www.tidymodels.org/find/parsnip/

doParallel::registerDoParallel()
titanic_rf_wf <- 
  workflow() %>% 
  add_recipe(titanic_recipe) %>% 
  add_model(titanic_rf_spec) %>% 
  fit_resamples(bootstraps(data = titanic_train, times = 25))



collect_metrics(titanic_rf_wf)

titanic_rf_last_wf <- 
  workflow() %>% 
  add_recipe(titanic_recipe) %>% 
  add_model(titanic_rf_spec)
final_fit <- 
  fit(object = titanic_rf_last_wf, 
      data = titanic_train)
final_fit %>% 
  extract_recipe(estimated = T)

final_fit %>%
  extract_fit_parsnip()

```



-------

## Tune a model

```{r}
library(tidyverse)
library(tidymodels)


titanic_train <- read_csv('https://bryantstats.github.io/math421/data/titanic.csv')
library(tidymodels)

# Setup the model
tune_spec <- 
  rand_forest(
    mtry = tune(),
    trees  = tune(),
    min_n = tune()
  ) %>% 
  set_engine("ranger") %>% 
  set_mode("classification")


# preprocessing
titanic_recipe <- 
  recipe(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked, 
         data = titanic_train) %>% # keep variables we want
  step_impute_median(Age,Fare) %>% # imputation
  step_impute_mode(Embarked) %>% # imputation
  step_mutate_at(Survived, Pclass, Sex, Embarked, fn = factor) %>% # make these factors
  step_mutate(Travelers = SibSp + Parch + 1) %>% # new variable
  step_rm(SibSp, Parch) %>% # remove variables
  step_dummy(all_nominal_predictors()) %>% # create indicator variables
  step_normalize(all_numeric_predictors()) # normalize numerical variables


doParallel::registerDoParallel()

# Train + Tune
tree_res <- 
  workflow() %>% 
  add_recipe(titanic_recipe) %>% 
  add_model(tune_spec) %>% 
  tune_grid(
    resamples = vfold_cv(titanic_train),
    grid = crossing(
      mtry = 3:5,
      trees  = seq(100, 200, 50),
      min_n  = seq(100, 300, 50)
    )
  )

# Plot the result
autoplot(tree_res)

tree_res %>% 
  collect_metrics()

tree_res %>%
  select_best("accuracy")
``` 

-------

## Compare models

```{r}
library(tidyverse)
library(tidymodels)


titanic_train <- read_csv('https://bryantstats.github.io/math421/data/titanic.csv')
library(tidymodels)

# preprocessing
titanic_recipe1 <- 
  recipe(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked, 
         data = titanic_train) %>% # keep variables we want
  step_impute_median(Age,Fare) %>% # imputation
  step_impute_mode(Embarked) %>% # imputation
  step_mutate_at(Survived, Pclass, Sex, Embarked, fn = factor) %>% # make these factors
  step_mutate(Travelers = SibSp + Parch + 1) %>% # new variable
  step_rm(SibSp, Parch) %>% # remove variables
  step_dummy(all_nominal_predictors()) # create indicator variables
  
  # preprocessing
  titanic_recipe2 <- 
  recipe(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked, 
         data = titanic_train) %>% # keep variables we want
  step_impute_mean(Age,Fare) %>% # imputation
  step_impute_mode(Embarked) %>% # imputation
  step_mutate_at(Survived, Pclass, Sex, Embarked, fn = factor) %>% # make these factors
  step_mutate(Travelers = SibSp + Parch + 1) %>% # new variable
  step_rm(SibSp, Parch) %>% # remove variables
  step_dummy(all_nominal_predictors())  # create indicator variables


  
  # preprocessing
  titanic_recipe3 <- 
  recipe(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked, 
         data = titanic_train) %>% # keep variables we want
  step_impute_median(Age,Fare) %>% # imputation
  step_impute_mode(Embarked) %>% # imputation
  step_mutate_at(Survived, Pclass, Sex, Embarked, fn = factor) %>% # make these factors
  step_mutate(Travelers = SibSp + Parch + 1) %>% # new variable
  step_rm(SibSp, Parch) %>% # remove variables
  step_dummy(all_nominal_predictors()) %>% # create indicator variables
  step_normalize(all_numeric_predictors()) # normalize numerical variables


# Setup the model
model1 <- 
  rand_forest(
    mtry = tune(),
    trees  = tune(),
    min_n = tune()) %>% 
  set_engine("ranger") %>% 
  set_mode("classification")

model2 <-
  decision_tree(
    cost_complexity = tune(),
    tree_depth = tune()) %>% 
  set_engine("rpart") %>% 
  set_mode("classification")

model3 <- 
  boost_tree(learn_rate=tune(),
             mtry = tune()) %>% 
  set_engine('xgboost') %>% 
  set_mode('classification')  

models_list <- 
  list(model1 = model1, 
       model2 = model2,
       model3 = model3)

all_workflows <- workflow_set(
  preproc = list(titanic_recipe1, titanic_recipe2, titanic_recipe3 ),
  models = models_list) %>% 
  workflow_map(resamples = bootstraps(titanic_train), grid = 10, verbose = TRUE)

rank_results(all_workflows, rank_metric = "roc_auc")


autoplot(all_workflows, metric = "roc_auc")
```

