---
title: "Embed shiny apps to Rmarkdown file"
author: "Son Nguyen"
date: "11/2/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## Embed shiny apps to Rmarkdown file. 

This is just to show that a shiny app can be embedded in a Rmarkdown file. To embed, insert a code cell (`Ctrl + Alt + I`) and copy the code of the app.  Knitt the rmardown file and choose `Yes, Always` when asked.  Below are a shiny app and its code. 

```{r, echo=FALSE, eval=FALSE}
library(tidyverse)
library(shiny)

d <- read_csv('https://covidtracking.com/data/download/all-states-history.csv')

write.csv(d, 'covid19.csv', row.names = FALSE)

preselected_states = c('CA', 'FL', 'TX', 'MA', 'NY', 'OH')

variables_names = names(d)

first_date = min(d$date)

current_date = max(d$date)
                     

ui <- fluidPage(
  
  titlePanel("Covid 19 by States"),

  sidebarLayout(
    
    sidebarPanel(
      
      checkboxGroupInput(inputId = "x", 
                         label = h3("Select state to compare"),
                         choices = preselected_states, 
                         selected = 'CA',
                         inline = TRUE),
      
      
      selectInput(inputId ='v1', 
                  label=h3('Select a Numeric Variable'),
                  choices=variables_names,
                  selected = 'positive'),
      
      sliderInput(inputId = "date",
                  label = h3("Select Date Range:"),
                  min = first_date,
                  max = current_date,
                  value= c(first_date, current_date),
                  timeFormat="%d %b"),
      
      radioButtons(inputId = "plot_choice", 
                   label = h3("Select Plot:"),
                   choices = c("Line Plot" = "line",
                               "Point Plot" = "point"),
                   selected = 'line'),
      
    ),
  
    mainPanel(
      
      imageOutput(outputId = 'show_plot')
    )
  )
)

# server is a function! 
server <- function(input, output) {
  
  output$show_plot <- renderPlot({
    
    library(tidyverse)
    library(ggplot2)
    library(gganimate)
    
    v1 = input$v1
    
    d <- d %>% 
      filter(state %in% input$x, date>input$date[1], date<input$date[2])
    
    if(input$plot_choice == 'line')
    {
      ggplot(d, aes_string(y=v1,
                           x='date',
                           color='state'))+ 
        geom_line()  
    }
    
    else{
      ggplot(d, aes_string(y=v1,
                           x='date',
                           color='state'))+ 
        geom_point()
    }
    
  }    
  )
}

shinyApp(ui = ui, server = server, options = list(height = 200))
```


```{r}
library(tidyverse)
library(shiny)

d = read_csv('titanic.csv')
variables_names = names(d)

#######################################
ui <- fluidPage(
  
  titlePanel("Density Plot for Titanic"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      selectInput(
        inputId ="var1",
        label = "Select a Numeric Variables",
        choices = variables_names, 
        selected = 'Age'
      ), 
      
      selectInput(
        inputId ="var2",
        label = "Select a Categorical Variables",
        choices = variables_names, 
        selected = 'Pclass'
      ),
      
      checkboxGroupInput(inputId = "embarked_location", 
                         label = "Select Embarked Location",
                         choices = names(table(d$Embarked)), 
                         selected = 'S',
                         inline = TRUE)
      
      
      
    ),
    
    
    mainPanel(
      
      plotOutput(outputId = 'show_plot')
      
    )
  )
)

#######################################
server <- function(input, output) {
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
    v2 = input$var2
    
    library(ggplot2)
    
    d <- d %>% filter(Embarked %in% input$embarked_location)
    
    ggplot(d, aes(x = d[[v1]], color = as.factor(d[[v2]])))+
      geom_density()+
      labs(x = v1, color = v2)
    
    
  })
  
}


#######################################
shinyApp(ui = ui, server = server, options = list(height = 500))
```

## Second App

```{r}
library(shiny)

######################################
# Set User Interface
ui <- fluidPage(
  titlePanel("Hello Shiny!"),
  
  sidebarLayout(
    
    sidebarPanel(
      sliderInput(
        inputId = "var1",
        label = "Decide the mean",
        min = 1,
        max = 100,
        value=10
      )
      
      ),
      
    mainPanel(
      # Output: Histogram ----
      plotOutput(outputId = 'show_plot')
    )
      
    )
    
  )
  

######################################
# Main codes for the app
server <- function(input, output) {
  
  output$show_plot <-renderPlot({
    m = input$var1
    hist(rnorm(mean=m, n=1000))
  }
  )

  
}

######################################
# Run the app
shinyApp(ui = ui, server = server, options = list(height = 1000))

```

