
---
output: 
  html_document:
  pdf_document: default
  word_document: default
title: "Assignment 14: Twitters Mining with rtweet"
---

***How to do it?***: 

- Open the Rmarkdown file of this assignment ([link](fa2021_assignment14.Rmd)) in Rstudio. 

- Right under each **question**, insert  a code chunk (you can use the hotkey `Ctrl + Alt + I` to add a code chunk) and code the solution for the question. 

- `Knit` the rmarkdown file (hotkey: `Ctrl + Alt + K`) to export an html.  

-  Publish the html file to your Githiub Page. 

***Submission***: Submit the link on Github of the assignment to Canvas

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
```


[Sample Codes](rtweet2.html)

-------

1. Pick a keyword or hashtag. Download the data associated with the keyword/hashtag. Plot at least 10 plots to visualize the data associated with the keyword/hashtag. All plots should have titles and captions. 

2. Choose a location then pick a trending keyword/hashtag in the location. Download the data associated with the keyword/hashtag. Plot at least 10 plots to visualize the data associated with the keyword/hashtag. All plots should have titles and captions. 
