---
title: "Animal Crossing reviews"
author: "Son Nguyen"
date: "11/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(tidytext)
library(tidyverse)

user_reviews <- readr::read_tsv("data/user_reviews.tsv")

user_reviews %>%
  count(grade) %>%
  ggplot(aes(grade, n)) +
  geom_col(fill = "midnightblue", alpha = 0.7)
```

```{r}
user_reviews
```



```{r}
user_reviews %>%
  filter(grade > 8) %>%
  sample_n(5) %>%
  pull(text)

```

# Word Frequency

```{r}
reviews_parsed <- user_reviews %>%
  mutate(text = str_remove(text, "Expand$")) %>%
  mutate(rating = case_when(
    grade > 7 ~ "good",
    TRUE ~ "bad"
  ))

```


```{r}
reviews_parsed

reviews_parsed %>% 
  unnest_tokens(word, text) %>% 
  anti_join(get_stopwords()) %>% 
  count(rating, word, sort = TRUE)

```

```{r}
reviews_parsed %>%
  unnest_tokens(word, text) %>% 
  anti_join(get_stopwords()) %>% 
  count(rating, word, sort = TRUE) %>% 
  group_by(rating) %>%
  slice_max(n, n = 10) %>% 
  ungroup() %>%
  mutate(word = reorder_within(word, by = n, within = rating)) %>%
  ggplot(aes(n, word, fill = rating)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~rating, scales = "free") +
  labs(x = "Contribution to sentiment",
       y = NULL)+
  scale_y_reordered() 
```

# Word Cloud

```{r}
library(wordcloud) # to render wordclouds
pal <- brewer.pal(8,"Dark2")

reviews_parsed %>%
  unnest_tokens(word, text) %>% 
  anti_join(get_stopwords()) %>% 
  count(rating, word, sort = TRUE) %>%
  with(wordcloud(word, n, random.order = FALSE, max.words = 50, colors=pal))

```

```{r}
library(wordcloud) # to render wordclouds
pal <- brewer.pal(8,"Dark2")

reviews_parsed %>%
  unnest_tokens(word, text) %>% 
  anti_join(get_stopwords()) %>% 
  count(rating, word, sort = TRUE) %>%
  filter(rating == 'good') %>% 
  with(wordcloud(word, n, random.order = FALSE, max.words = 50, colors=pal))
```
```{r}
library(wordcloud) # to render wordclouds
pal <- brewer.pal(8,"Dark2")

reviews_parsed %>%
  unnest_tokens(word, text) %>% 
  anti_join(get_stopwords()) %>% 
  count(rating, word, sort = TRUE) %>%
  filter(rating == 'bad') %>% 
  with(wordcloud(word, n, random.order = FALSE, max.words = 50, colors=pal))
```


## Sentiment Analysis

```{r}
reviews_parsed %>%
    unnest_tokens(word, text) %>% 
    anti_join(get_stopwords()) %>% 
    count(rating, word, sort = TRUE) %>%
    group_by(rating) %>% 
    inner_join(get_sentiments("nrc")) %>%
    filter(!is.na(sentiment)) %>%
    count(sentiment, sort = TRUE) %>% 
    group_by(rating) %>% 
    mutate(n = n/sum(n)) %>% 
    ggplot(aes(sentiment, n, fill=rating))+geom_col(position = 'dodge')+
    labs(y='Relative Frequency')
```

```{r}
reviews_parsed %>%
    unnest_tokens(word, text) %>% 
    anti_join(get_stopwords()) %>% 
    count(rating, word, sort = TRUE) %>%
    group_by(rating) %>% 
    inner_join(get_sentiments("bing")) %>%
    filter(!is.na(sentiment)) %>%
    count(sentiment, sort = TRUE) %>% 
    group_by(rating) %>% 
    mutate(n = n/sum(n)) %>% 
    ggplot(aes(sentiment, n, fill=rating))+geom_col(position = 'dodge')+
    labs(y='Relative Frequency')
```
```{r}
reviews_parsed %>%
    unnest_tokens(word, text) %>% 
    anti_join(get_stopwords()) %>% 
    count(rating, word, sort = TRUE) %>%
    group_by(rating) %>% 
    inner_join(get_sentiments("afinn")) %>%
    mutate(sentiment = value) %>% 
    filter(!is.na(sentiment)) %>%
    count(sentiment, sort = TRUE) %>% 
    group_by(rating) %>% 
    mutate(n = n/sum(n)) %>% 
    ggplot(aes(sentiment, n, fill= rating))+geom_col(position = 'dodge')+
    labs(y='Relative Frequency')
```
## Modeling

```{r}
library(caret)
set.seed(2020)
library(themis)
library(yardstick)

df <- reviews_parsed %>% select(rating, text)
library(textrecipes)

a <- recipe(rating~text,
       data = df) %>% 
  step_tokenize(text) %>% 
  step_tokenfilter(text, max_tokens = 50) %>% 
  step_tfidf(text) %>% 
  step_normalize(all_numeric_predictors()) %>% 
  step_smote(rating) %>% 
  prep()

df <- juice(a)
names(df)[names(df)=='rating'] <- 'target'


splitIndex <- createDataPartition(df$target, p = .10, 
                                  list = FALSE)
df_train <- df[ splitIndex,]
df_test <- df[-splitIndex,]

forest_ranger <- train(target~., data=df_train, 
                        method = "ranger")

pred <- predict(forest_ranger, df_test)

cm <- confusionMatrix(data = pred, reference = df_test$target)
cm$overall[1]

d = data.frame(pred = pred, obs = df_test$target)

d %>% conf_mat(pred, obs) %>% autoplot()
```

