
---
output: 
  html_document:
  pdf_document: default
  word_document: default
title: "Final Project - Building Shiny Apps"
---

-------

**Submission Guideline:**  Include to your Github page the link of the app for each question from 1-12. You could also embed all your shiny apps in an Rmarkdown.  See the note under Question 4 for how to embed shiny apps in a Rmarkdown file.

-------

### Question 1. Create an empty dashboard. In Rstudio, File -> New File -> R Markdown -> From Template -> Flex Dashboard. Knit the rmarkdown file and add the html link to this report. 

### Question 2. Use [this flex rmarkdown template](https://bryantstats.github.io/math421/final/flex_template.Rmd) to create a flex dashboard that

- Has at least 4 different plotly graphs

- Has at least two main Tab

- Shows a table data that can be searched

- Has a side bar

### Question 3. We want users to be able to interact with our dashboard.  This can be done using `shiny`. Follow these below steps to create a shiny flex dashboard then publish it to the Internet. 

- Install the following packages `shiny`, `packrat`, `rsconnect`. 

- Go to https://www.shinyapps.io/ and create an account 

- Go to https://www.shinyapps.io/admin/#/dashboard.  Account -> Tokens -> Show -> Show secret-> Copy the secret code. 

It should look like this


```{r, eval=FALSE}
rsconnect::setAccountInfo(name='fall20',
			  token='E130D64F22776383660DA7EA5251EC04',
			  secret='mJI7rgq2Wf46g2Wf46g2WNOa+E6NRqr26yG3N5')
```

- Paste the secret code into Rstudio Consile and Run it. 

- Download a sample shiny flex dashboard:  

-------

### Question 2 - selectInput

Write a shiny app that can plot barplot of two categorical variables in the titanic dataset, [Example of the barplot](https://bryantstats.github.io/math421/slides/6_viz.html#39).

[Similar Apps](https://fa20.shinyapps.io/selectinput/) and [Codes](shiny_fa21/selectinput/a2.R)

Notice:  

- Two different shiny apps should be in two different folders. 

- You should not use local path when reading a data file.  For example,  do not use `read_csv('C://final//titanic.csv')`.  Instead, create a new folder and put the data file (titanic.csv) and the code file in the folder just created and use `read_csv('titanic.csv')`

-------

### Question 3 - checkboxGroupInput

Write a shiny app that creates a plot for the adult census dataset. The user inputs two variables and can choose a tick on some options of a variable (i.e., use`checkboxGroupInput`). 

[Similar Apps](https://fa20.shinyapps.io/checkboxGroupInput/) and [Codes](shiny_fa21/checkboxGroupInput/a2_3.R)

-------

### Question 4 - sliderInput

Write a shiny app that creates a plot for the adult census dataset.  The user inputs two variables and can change the range of `Age` (i.e., use `sliderInput`). 

[Similar Apps](https://sonfed.shinyapps.io/sliderInput/) and [Codes](shiny_fa21/sliderInput/a2_1.R)

-------

Notice:  You can only run 5 apps on shinyapps.io.  If you are running out of apps, you are recommended to create another shiny account and use multiple accounts.  

You could also embed all your shiny apps in an Rmarkdown.  Do the follows to embed an shiny app to an rmarkdown. 

- Create an Rmarkdown

- Insert a code cell (`Ctrl + Alt + I`)

- Copy the codes of the shiny to the code cell

- Knit it 

- When asked, choose `Yes, Always.`

- Here is an example: https://fa20.shinyapps.io/a9_markdown/


-------

### Question 5 - dateRangeInput

Use the WHO-Covid19 data, write a shiny app that shows statistics of Covid19 for any three countries selected by the user.  The user can also change the range of the dates.  Notice:  you may want to use selectInput instead of checkboxGroupInput for the user to select countries. 

[Similar App](https://sonfed.shinyapps.io/dateRangeInput2/), 
[Codes](shiny_fa21/dateRangeInput2/3.R), and 
[Data](shiny_fa21/dateRangeInput2/who_covid.csv)

-------

### Question 6 - radioButtons

Write a shiny app that creates plots for the adult census dataset. The user inputs two variables and can choose a multiple choice option (i.e., use`radioButtons`). 

[Similar Apps](https://sonfed.shinyapps.io/radioButtons/) and [Codes](shiny_fa21/radioButtons/a2_2.R)

-------

### Question 7 - navbarPage

Write a shiny app that creates plots for the adult census data. Make use of the `navbarPage`

This below example shows how to use `navbarPage`

[Example App](https://sonfed.shinyapps.io/navbarPage/) and 
[Codes](shiny_fa21/navbarPage/a2_4.R)

-------

### Question 8 - Uploaded Data

Write a shiny app that can plot barplot of two categorical variables in an uploaded dataset, [Example of the barplot](https://bryantstats.github.io/math421/slides/6_viz.html#39). 

Use this data to test your app: [Adult Census Data](data/adult_modified.csv)

[Similar Apps](https://fa20.shinyapps.io/uploaded_data/) and [Codes](shiny_fa21/uploaded_data/a3.R)

-------

### Question 9 - Uploaded Data

Write a shiny app that can plot the scatter plot of two numeric variables and colored by a categorical variable in an uploaded dataset. Example of the plot: https://bryantstats.github.io/math421/slides/6_viz.html#15

Use this data to test your app: [Adult Census Data](data/adult_modified.csv)


-------

### Question 10

Write a shiny app on own selected data.  Make uses of  `selectInput`,  `radioButtons`, `checkboxGroupInput` and `sliderInput`. 


-------

### Question 11

Write a shiny app on own selected data.  Make uses of `selectInput`, `radioButtons`, `checkboxGroupInput` and `dateRangeInput`. 


-------

### Question 12

Write an app that make uses of `selectInput`, `sliderInput` or `dateRangeInput` or both, `radioButtons`, `checkboxGroupInput`  and `navbarPage`. You might use multiple datasets for the app. 

-------

### Question 13 - Presentation

Present your shiny app in Question 12 on the final exam day. 

- Present the features of your app 

- Discuss the codes of the apps. 

- Discuss any error or challenge you had to overcome

- Give an advice for anyone who is about to do this project

- The presentation should be accessible to ones that have no experience with shiny coding but know R. 

-------

### References


Check out Shiny official tutorial: https://shiny.rstudio.com/tutorial/

Check out Shiny Galary: https://shiny.rstudio.com/gallery/

Pairs of render and output: https://bookdown.org/weicheng/shinyTutorial/images/outputs.png

Check out some shiny layouts here: https://shiny.rstudio.com/articles/layout-guide.html

Check out shiny dynamic UI here

https://shiny.rstudio.com/gallery/dynamic-ui.html

https://shiny.rstudio.com/articles/dynamic-ui.html

-------